Jethro/com 215/load testing
COMP4350-Team2/Backend pull request #40
Opened 2024-12-04 14:25 UTC by Jethro-Swanson

Locust Load testing code, has feature branch merged in so that should be merged first

2024-12-04 22:53 UTC, gapy04 requested changes

2024-12-04 22:53 UTC, gapy04 commented on requirements.txt
> +locust==2.32.3
Order this alphabetically.

2024-12-04 22:53 UTC, gapy04 commented on README.md
> +for host put the aws instace url/ip with the port ie http://2.4.5.7:6060 (this is not the actual ip)
Fix typos. "instance" and "i.e."

2024-12-04 22:53 UTC, gapy04 commented on locustfile.py
In general,
1. Replace all double quotes " with single quotes ' to follow pep8 standards (unless block comment).
2. Remove commented out logging.info if we are not actually using it.
3. Add a block comment for all function (def) in the following format:
```
"""
Description

Args:
    If any besides self
    arg1: description of the arg

Returns:
    What it returns if it does return something
"""
```

2024-12-04 22:53 UTC, gapy04 commented on locustfile.py
> +from utils.env_helper import load_env_variables
Reorder imports.

It should always be python native libraries i.e. os and logging, followed by third party libraries such as locust, and then code from us (i.e. utils.env_helper).

2024-12-04 22:53 UTC, gapy04 commented on locustfile.py
Run flake8 and fix any errors

2024-12-05 03:32 UTC, gapy04 requested changes

2024-12-05 03:32 UTC, gapy04 commented on locustfile.py
> +    """
Put the block comment inside the function (right under the `def all_api(self)`). Do this for the other block comment too.

2024-12-05 03:32 UTC, gapy04 commented on locustfile.py
> +            print_str += '_'+str(self.user_id)+'@gmail.com'
add a space between the operators here like we do in other places. Specifically, like `+ str(self.user_id)`

2024-12-05 03:32 UTC, gapy04 commented on locustfile.py
> +            username += '_'+str(self.user_id)+'@gmail.com'
Same thing as above, add space between the operators.

2024-12-05 21:56 UTC, gregoryvm approved these changes

2024-12-05 22:43 UTC, gapy04 approved these changes

2024-12-05 22:44 UTC, merged